pipeline:
  - name: zillot
    watchdog: 600
    git:
      url: https://github.com/mirmik/zillot
      name: zillot
    steps:
      - name: make
        run: ./make.py

      - name: test
        run: ./runtests

      - name: licant-libs
        run: licant-libs .

      - name: install stm test
        run: ./make.py stm32_install_test

      - name: restart stm
        run: |
          st-util &
          sleep 1
          killall st-util

      - name: run stm test
        run: /home/mirmik/project/onboardtest/onboardtest-listener /dev/ttyACM0

    success_info: "Pipeline: {{pipeline_name}}\nCommit: {{commit_hash}}\nMessage: {{commit_message}}\n"
